### ISSUE TITLE
I can not get your sample .kitchen.yml to work.

### ISSUE THREAD

**Issue by sqorbrody** [test-kitchen/kitchen-google#15]
This looks to be a problem with fog but I am not sure.  Any help would be much appreciated. 
...
bundle exec kitchen converge
-----> Starting Kitchen (v1.3.1)
/Users/brody/.rvm/gems/ruby-2.2.0@sqor02/gems/fog-1.23.0/lib/fog/rackspace/mock_data.rb:42: warning: duplicated key at line 80 ignored: "name"
-----> Creating <default-debian-7>...

> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > ## Message: Failed to complete #create action: [uninitialized constant Fog::VERSION]
> > > > > > 
> > > > > > Please see .kitchen/logs/kitchen.log for more details
> > > > > > Also try running `kitchen diagnose --all` for configuration

**Comment by anl** [comment]
Thanks for opening the issue - would you be able to post a Gist of your Gemfile.lock so I can replicate your environment?

**Comment by sqorbrody** [comment]
I added both my Gemfile and resulting Gemfile.lock. 
https://gist.github.com/sqorbrody/dd7a62c1042658a70420

I am running OSX 10.10.3,  I will be testing the same setup in ubuntu 14.04 later on this week,  I will keep you informed.

**Comment by sqorbrody** [comment]
Any update on this?

**Comment by spudnic** [comment]
I would really like to use gce but with out this I can not properly evaluate the product.  Can some one help me.  :)

**Comment by robbkidd** [comment]
Many moons have passed and a few versions released since this issue was opened. With the rename'n'release of `kitchen-google` and its rewrite to replace `fog` with `google-api-client`, I suspect this error has been overcome by events. Closing this issue.

@spudnic If you're still using test-kitchen and GCE and are having any trouble, please let us know!
