### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by manuelmazzuola** [test-kitchen/kitchen-google#19]
Is windows supported ? I guess not.
Are you going to support it ?

**Comment by manuelmazzuola** [comment]
I've seen that kitchen supports winrm transport but the windows images on gce does not support winrm connections.
A future implementation should provision a windows image and use a startup script (https://cloud.google.com/compute/docs/startupscript) like this 

```
netsh advfirewall firewall add rule name="winrm" dir=in action=allow protocol=TCP localport=5985                                                            
winrm quickconfig -q                                                                                                                                        
winrm set winrm/config/service @{AllowUnencrypted="true"}                                                                                                   
winrm set winrm/config/service/auth @{Basic="true"}
```

**Comment by tas50** [comment]
We do have windows support so I'm going to close this one out. If anyone comes up with specific areas where our support is lacking feel free to open detailed issues outlining what's lacking.
