### ISSUE TITLE
setting scope on service accounts

### ISSUE THREAD

**Issue by cwaddingham** [test-kitchen/kitchen-google#20]
We've run into an issue using the gce driver where the service account does not have sufficient permissions call the gsutil tools. It looks like the problem is with setting the proper scope for the service account within the .kitchen.yml file. Has anyone else run into this problem? And if so, how did you overcome it?

**Comment by CodeSathyaKumar** [comment]
Got stuck with the same issue. You managed to get over it ?

**Comment by cheeseplus** [comment]
Closing this one due to lack of response and age. Please open a new issue with current versions if this is still a problem.
