### ISSUE TITLE
Unsupported parameters are silently ignored

### ISSUE THREAD

**Issue by Temikus** [test-kitchen/kitchen-google#23]
I think users should know when their parameters are not actually applied:

```
platforms:
  - name: debian-7
    driver_config:
      image_name: debian-7-wheezy-v20151104
      require_chef_omnibus: true
      public_key_path: '/Users/temikus/.ssh/id_rsa.pub'
      auto_restart: true
      tags: ["kitchen"]

λ bundle exec kitchen create
-----> Starting Kitchen (v1.4.2)
-----> Creating <default-debian-7>...
       GCE instance <default-debian-7-cff9e788-b3b3-49d3-a156-40e761981e4f> created.
.....       (server ready)
       [SSH] Established
       (ssh ready)
       Finished creating <default-debian-7> (0m45.41s).
-----> Kitchen is finished. (0m46.15s)
```

**Comment by cheeseplus** [comment]
Trying to chase down invalid options by checking everything is a losing battle when ultimately having a correct config and good error messages when misconfiguration causes it to explode is the best defense against this problem. Chasing it the other way never ends well and it'd be a lot of code / gold plating for something that ultimately will be a moving target.
