### ISSUE TITLE
Transition to fog-google

### ISSUE THREAD

**Issue by Temikus** [test-kitchen/kitchen-google#24]
Currently, fog pulls in way too many dependencies and since version 1.30 it pulls fog-google anyway.

Also, preemptible option became available in fog-google 0.0.7, which theoretically leaves a small point of failure in dependencies. This will need to be checked and, if possible - locked in.

**Comment by anl** [comment]
@adamleff has sent a PR using google-api-client instead of fog-google in #30 - thoughts/comments?

**Comment by Temikus** [comment]
@anl Adam is from the Chef Partner team and I would defer on their opinion when it comes to KitchenCI to be honest.
Google-api-client can be tougher to work with but I cannot deny the speed increase and lowering the dependency count, as well as aligning more closely with the current implementation of knife.

If you feel differently - do speak up, since you're the current owner, but I would probably close this bug when their PR makes it in.

**Comment by cheeseplus** [comment]
As the google-api-client has made it in, this can be closed.
