### ISSUE TITLE
Cut new gem version with Preemptible support

### ISSUE THREAD

**Issue by Temikus** [test-kitchen/kitchen-google#29]
@marcy-terui asked when the new version is going to be released in #22
Since I'm not in the gem owners, summoning the owners: @anl , @tyler-ball , @someara 

Hi Andrew, Sean, Tyler,

Can a new gem release be cut so we have preemptible support?
What are the conditions that need to be met before the release (if any)?

Thanks!

P.S. While we're at it - maybe it makes sense to rename the gem to kitchen-google for consistency sake?

**Comment by Temikus** [comment]
+ FYI @mbrukman @erjohnso

**Comment by marcy-terui** [comment]
@Temikus Thank you for your quick reply!

Hello @someara, @tyler-ball, 

Please release #22 if you have a time.
I'm not in a hurry.
But, I might make a different implementation if it's too delayed.
Because I want to add(change) some features.

Thanks.

**Comment by marcy-terui** [comment]
Any updates? @someara @tyler-ball

**Comment by tyler-ball** [comment]
I'm going to ping @cheeseplus - he has been doing all the Test Kitchen maintenance recently

**Comment by someara** [comment]
It doesn't look like there's a kitchen-google release on Rubygems at all,
actually.

Let's use this thread to sort out everyone who should have commit and
release bits.

What are everyone's Github and Rubygems account names?

-s

**Comment by Temikus** [comment]
The current gem is published under Kitchen-GCE:
https://rubygems.org/gems/kitchen-gce

I don't know why exactly it's not kitchen-google, but @erjohnso and @mbrukman may give some more context on that. If there's no particular reason or it's no longer relevant I strongly vote for the gem name to mimic the name of the repo to avoid confusion, e.g. kitchen-google

My rubygems account, github is the same - temikus:
https://rubygems.org/profiles/temikus

**Comment by marcy-terui** [comment]
@tyler-ball @someara Thanks for your reply.

I agree with @Temikus about the name of gem and repo.

My account name in GitHub and RubyGems is the same - `marcy-terui`
https://rubygems.org/profiles/marcy-terui

**Comment by erjohnso** [comment]
This was the [old issue](https://github.com/test-kitchen/kitchen-google/issues/16) to move Andrew's project over to Test Kitchen.  I think we'd all prefer to see the gem match the repo.

Perhaps we can just make a new gem called kitchen-google?  Seems that the kitchen-gce gem still points to Andrew's old/defunct repo.

My account is: https://rubygems.org/profiles/erjohnso

**Comment by anl** [comment]
Is there anything I can do to help here?

**Comment by erjohnso** [comment]
Hi @anl!

Perhaps. Is it possible to rename the rubygem, update the metadata, and add some backup humans to roll new releases?  Alternatively, I think we could spin up a new gem and then delete the defunct kitchen-gce gem.

wdyt?

**Comment by Temikus** [comment]
If I may add one suggestion - if we go the route of "spin up a new gem and delete the old gem", can we push a version bump of the old gem with a deprecation notifier, so people at least know what to switch to?

For example, at least add a post_install_message:
```
gem.post_install_message = <<-MESSAGE
!    The 'kitchen-gce' gem has been deprecated and has been replaced by 'kitchen-google'.
!    See: https://rubygems.org/gems/kitchen-google
!    And: https://github.com/test-kitchen/kitchen-google
MESSAGE
```

**Comment by anl** [comment]
@erjohnso @Temikus My schedule is full today (and I can't do test-kitchen work at $DAYJOB) but I will tackle this tomorrow.  Agreed that a deprecation notifier is a good way to go.

**Comment by Temikus** [comment]
@anl Thank you very much! If you need any help - let me know, I'd be happy to!

**Comment by marcy-terui** [comment]
@anl That would be great :+1:  Thank you very much :smile: !

**Comment by mbrukman** [comment]
My account is also the same as on GitHub: https://rubygems.org/profiles/mbrukman

**Comment by anl** [comment]
I've released kitchen-google v0.3.0 on Rubygems; @mbrukman, I made you an owner for that gem and kitchen-gce also.

I have not yet added a deprecation notice to kitchen-gce - I'll do that shortly, once I have time to do a little more than a smoke test with kitchen-google.  I did notice that Travis needs some cleanup on Ruby 1.9, and the README could use a little cleanup too.

**Comment by erjohnso** [comment]
Awesome, thank you @anl!

**Comment by mbrukman** [comment]
Thank you, @anl! :+1:

**Comment by marcy-terui** [comment]
:+1: :+1: :+1:

**Comment by robbkidd** [comment]
Reviewing issues, it looks like [preemptible support](https://github.com/test-kitchen/kitchen-google/blob/master/lib/kitchen/driver/gce.rb#L426-L444) is in the latest `kitchen-google` and this issue is still open to track the action of releasing one more `kitchen-gce` with a deprecation notice. Is that right?

**Comment by tas50** [comment]
Closing this out since releasing a deprecation warning in kitchen-gce is outside the scope of this repo. We're now regularly releasing this gem and it ships in Chef Workstation.
