### ISSUE TITLE
Add @erjohnso and @adamleff to kitchen-google repo and gem

### ISSUE THREAD

**Issue by anl** [test-kitchen/kitchen-google#31]
Give @erjohnso and @adamleff access to kitchen-google repo and gem.

**Comment by anl** [comment]
@erjohnso It looks like you are already a member of kitchen-google-admins so you should have access - can you confirm?

**Comment by anl** [comment]
Added @adamleff to collaborators.

**Comment by anl** [comment]
@erjohnso Can you confirm you are https://rubygems.org/profiles/erjohnso on RubyGems?

@adamleff Can you confirm you are https://rubygems.org/profiles/adamleff on RubyGems?

**Comment by adamleff** [comment]
Confirmed!  That's me! (adam at leff dot co - not com)

**Comment by erjohnso** [comment]
@anl - yes, confirmed I'm a member of https://github.com/orgs/test-kitchen/teams/kitchen-google-admins.

Also, yes, https://rubygems.org/profiles/erjohnso is my ruby profile.

Thank you very much!

**Comment by anl** [comment]
@adamleff and @erjohnso - I've added you both as Gem owners now.

**Comment by adamleff** [comment]
Thank you, @anl! Unless you have a concern, I'd like to do a 1.0.0 release sometime today.

**Comment by erjohnso** [comment]
Thank you @anl!  (and thanks for cutting the new gem @adamleff). :+1:

**Comment by anl** [comment]
(Belatedly) no objections here - especially now with your fixes for #32 - thanks @adamleff.
