### ISSUE TITLE
Allow instance_name prefix to be customizable

### ISSUE THREAD

**Issue by ghost** [test-kitchen/kitchen-google#40]
Description

It very important for us to have ability change "tk-" prefix. It will help us correspond our naming convention.

ChefDK Version

Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3

ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
Platform Version

Centos 6.7

Replication Case

Create any instance in google cloud and you will see hostname eg. "tk-..."

Kitchen Output

-----> Creating ...
Creating GCE instance in project ......................, zone ...............
Zone operation ................................. created. Waiting for it to complete...
Current status: PENDING
Current status: RUNNING
Current status: DONE

It will be great if default prefix stay like "tk-" and will be changed over some additional attribute

**Comment by jjasghar** [comment]
This shouldn't be too hard to add this feature. At the same time, `tk-` instances are supposed to be throw away, are you using it for deployment and are these instances long lived?

**Comment by jjasghar** [comment]
Also, isn't this: https://github.com/test-kitchen/kitchen-google/pull/37 what you'd like?

**Comment by bartanxas** [comment]
Yes, and it depends. But main reason is internal name convention.

**Comment by bartanxas** [comment]
Yes, that's it.

**Comment by robbkidd** [comment]
Implemented in #54
