### ISSUE TITLE
Ability to support image-family

### ISSUE THREAD

**Issue by eovolkov** [test-kitchen/kitchen-google#41]
Can you add feature to support image-family which like in gcloud:

--image-family IMAGE_FAMILY
        The family of the image that the boot disk will be initialized with.
        When a family is specified instead of an image, the latest
        non-deprecated image associated with that family is used.

**Comment by whiteley** [comment]
I'm interested in implementing this.

Question for the maintainers: I've looked at doing it a few ways but keep coming back to breaking the current _alias_ support. Since GCP's own use of image aliases is deprecated, would that be an acceptable path to go?
