### ISSUE TITLE
Disable instance_name suffix generation

### ISSUE THREAD

**Issue by hartfordfive** [test-kitchen/kitchen-google#46]
At this location:
https://github.com/test-kitchen/kitchen-google/blob/master/lib/kitchen/driver/gce.rb#L330

A random suffix is automatically added to the end of the instance name.  Why I understand the reason, I think it would be good to allow the user to have the option of preventing this and have the ability to specify the whole instance name.  This would be beneficial in the case such as where you're using test kitchen to provision a test Zookeeper cluster.  Because you can never know the instance names ahead of time, you can't set DNS entries that will work.  Maybe adding an attribute such as `disable_auto_suffix_generation` could be added to allow this functionality?

**Comment by cheeseplus** [comment]
#37 will take care of this one.

**Comment by robbkidd** [comment]
Resolved with the ability to set a custom instance name in #54.
